adb shell
pm uninstall -k --user 0 com.samsung.aasaservice
pm uninstall -k --user 0 com.sec.hearingadjust
pm uninstall -k --user 0 com.samsung.android.aremoji
pm uninstall -k --user 0 com.samsung.android.authfw
pm uninstall -k --user 0 com.samsung.android.tapack.authfw
pm uninstall -k --user 0 com.sec.android.autodoodle.service
pm uninstall -k --user 0 com.sec.android.app.DataCreate
pm uninstall -k --user 0 com.sec.android.provider.badge
pm uninstall -k --user 0 com.samsung.android.sm.devicesecurity
pm uninstall -k --user 0 com.samsung.android.bbc.bbcagent
pm uninstall -k --user 0 com.samsung.android.visionintelligence
pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
pm uninstall -k --user 0 com.sec.android.app.bluetoothtest
pm uninstall -k --user 0 com.samsung.storyservice
pm uninstall -k --user 0 com.samsung.android.callbgprovider
pm uninstall -k --user 0 com.sec.factory.cameralyzer
pm uninstall -k --user 0 com.samsung.android.app.omcagent
pm uninstall -k --user 0 com.samsung.android.sdm.config
pm uninstall -k --user 0 com.samsung.android.providers.carrier
pm uninstall -k --user 0 com.wssyncmldm
pm uninstall -k --user 0 com.sec.android.soagent
pm uninstall -k --user 0 com.samsung.android.knox.containeragent
pm uninstall -k --user 0 com.samsung.android.knox.containercore
pm uninstall -k --user 0 com.samsung.android.uds
pm uninstall -k --user 0 com.samsung.android.aware.service
pm uninstall -k --user 0 com.samsung.android.app.sharelive
pm uninstall -k --user 0 com.samsung.android.mobileservice
pm uninstall -k --user 0 com.sec.android.app.ve.vebgm
pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
pm uninstall -k --user 0 com.samsung.android.cidmanager
pm uninstall -k --user 0 com.samsung.android.cmfa.framework
pm uninstall -k --user 0 com.samsung.cmh
pm uninstall -k --user 0 com.mediatek
pm uninstall -k --user 0 com.mediatek.systemuiresoverlay
pm uninstall -k --user 0 com.samsung.android.knox.attestation
pm uninstall -k --user 0 com.samsung.android.networkstack.tethering.overlay
pm uninstall -k --user 0 com.samsung.android.smartswitchassistant
pm uninstall -k --user 0 com.samsung.android.wifi.resources
pm uninstall -k --user 0 com.samsung.android.wifi.softap.resources
pm uninstall -k --user 0 com.sec.bcservice
pm uninstall -k --user 0 com.sec.enterprise.knox.attestation
pm uninstall -k --user 0 com.sec.epdg
pm uninstall -k --user 0 com.samsung.SMT
pm uninstall -k --user 0 com.samsung.android.container
pm uninstall -k --user 0 com.samsung.sec.android.application.csc
pm uninstall -k --user 0 com.samsung.android.livestickers
pm uninstall -k --user 0 com.sec.android.app.factorykeystring
pm uninstall -k --user 0 com.sec.factory
pm uninstall -k --user 0 com.sec.android.diagmonagent
pm uninstall -k --user 0 com.samsung.android.themecenter
pm uninstall -k --user 0 com.samsung.android.dynamiclock
pm uninstall -k --user 0 com.samsung.android.rubin.app
pm uninstall -k --user 0 com.samsung.android.easysetup
pm uninstall -k --user 0 com.microsoft.appmanager
pm uninstall -k --user 0 com.samsung.android.dqagent
pm uninstall -k --user 0 com.sec.android.app.parser
pm uninstall -k --user 0 com.samsung.android.da.daagent
pm uninstall -k --user 0 com.sec.android.emergencymode.service
pm uninstall -k --user 0 com.sec.android.provider.emergencymode
pm uninstall -k --user 0 com.sec.enterprise.mdm.services.simpin
pm uninstall -k --user 0 com.sec.epdgtestapp
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.samsung.faceservice
pm uninstall -k --user 0 com.samsung.android.aircommandmanager
pm uninstall -k --user 0 com.sec.factory.camera
pm uninstall -k --user 0 com.samsung.android.app.galaxyfinder
pm uninstall -k --user 0 com.sec.android.app.samsungapps
pm uninstall -k --user 0 com.samsung.android.themestore
pm uninstall -k --user 0 com.samsung.android.mdecservice
pm uninstall -k --user 0 com.samsung.android.sdk.handwriting
pm uninstall -k --user 0 com.samsung.android.hdmapp
pm uninstall -k --user 0 com.sec.android.app.SecSetupWizard
pm uninstall -k --user 0 com.sec.android.app.hwmoduletest
pm uninstall -k --user 0 com.sec.imsservice
pm uninstall -k --user 0 com.samsung.advp.imssettings
pm uninstall -k --user 0 com.sec.imslogger
pm uninstall -k --user 0 com.samsung.ipservice
pm uninstall -k --user 0 com.samsung.android.arzone
pm uninstall -k --user 0 com.samsung.klmsagent
pm uninstall -k --user 0 com.samsung.android.knox.analytics.uploader
pm uninstall -k --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall -k --user 0 com.samsung.knox.keychain
pm uninstall -k --user 0 com.samsung.android.knox.pushmanager
pm uninstall -k --user 0 com.knox.vpn.proxyhandler
pm uninstall -k --user 0 com.samsung.android.mdx
pm uninstall -k --user 0 com.samsung.android.app.simplesharing
pm uninstall -k --user 0 com.samsung.android.bluelightfilter
pm uninstall -k --user 0 com.samsung.android.localeoverlaymanager
pm uninstall -k --user 0 com.sec.app.RilErrorNotifier
pm uninstall -k --user 0 com.samsung.android.mcfds
pm uninstall -k --user 0 com.samsung.android.mdx.kit
pm uninstall -k --user 0 com.samsung.android.mdm
pm uninstall -k --user 0 com.samsung.android.mdx.quickboard
pm uninstall -k --user 0 com.samsung.android.net.wifi.wifiguider
pm uninstall -k --user 0 com.samsung.android.server.wifi.mobilewips
pm uninstall -k --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall -k --user 0 com.netflix.mediaclient
pm uninstall -k --user 0 com.samsung.android.networkdiagnostic
pm uninstall -k --user 0 com.samsung.android.networkstack
pm uninstall -k --user 0 com.samsung.android.service.peoplestripe
pm uninstall -k --user 0 com.sec.vsim.ericssonnsds.webapp
pm uninstall -k --user 0 com.sec.android.app.personalization
pm uninstall -k --user 0 com.samsung.android.privateshare
pm uninstall -k --user 0 com.sec.android.app.fm
pm uninstall -k --user 0 com.sec.android.widgetapp.webmanual
pm uninstall -k --user 0 com.osp.app.signin
pm uninstall -k --user 0 com.sec.android.app.billing
pm uninstall -k --user 0 com.samsung.android.scloud
pm uninstall -k --user 0 com.samsung.android.scs
pm uninstall -k --user 0 com.samsung.android.app.spage
pm uninstall -k --user 0 com.samsung.android.mateagent
pm uninstall -k --user 0 com.sec.location.nsflp2
pm uninstall -k --user 0 com.samsung.android.mcfserver
pm uninstall -k --user 0 com.samsung.android.samsungpass
pm uninstall -k --user 0 com.samsung.android.spayfw
pm uninstall -k --user 0 com.sec.spp.push
pm uninstall -k --user 0 com.samsung.android.smartsuggestions
pm uninstall -k --user 0 com.samsung.android.sm.policy
pm uninstall -k --user 0 com.samsung.android.securitylogagent
pm uninstall -k --user 0 com.sec.sve
pm uninstall -k --user 0 com.sec.android.app.servicemodeapp
pm uninstall -k --user 0 com.sec.android.RilServiceModeApp
pm uninstall -k --user 0 com.sec.android.app.setupwizardlegalprovider
pm uninstall -k --user 0 com.samsung.ims.smk
pm uninstall -k --user 0 com.samsung.android.location
pm uninstall -k --user 0 com.samsung.android.smartcallprovider
pm uninstall -k --user 0 com.sec.android.easyMover.Agent
pm uninstall -k --user 0 com.samsung.android.smartmirroring
pm uninstall -k --user 0 com.samsung.android.smartface
pm uninstall -k --user 0 com.samsung.android.beaconmanager
pm uninstall -k --user 0 com.samsung.android.service.stplatform
pm uninstall -k --user 0 com.sec.android.app.soundalive
pm uninstall -k --user 0 com.samsung.android.stickercenter
pm uninstall -k --user 0 com.samsung.android.svcagent
pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
pm uninstall -k --user 0 com.samsung.android.tadownloader
pm uninstall -k --user 0 com.samsung.android.accessibility.talkback
pm uninstall -k --user 0 com.trustonic.teeservice
pm uninstall -k --user 0 com.sec.automation
pm uninstall -k --user 0 com.sec.android.daemonapp
pm uninstall -k --user 0 com.samsung.safetyinformation
pm uninstall -k --user 0 com.samsung.knox.securefolder
pm uninstall -k --user 0 com.samsung.android.forest
pm uninstall -k --user 0 com.samsung.android.fmm
pm uninstall -k --user 0 com.samsung.memorysaver
pm uninstall -k --user 0 com.samsung.android.kidsinstaller
pm uninstall -k --user 0 com.sec.android.preloadinstaller
pm uninstall -k --user 0 com.samsung.android.aremojieditor
pm uninstall -k --user 0 com.sec.android.app.safetyassurance
pm uninstall -k --user 0 com.samsung.android.icecone
pm uninstall -k --user 0 com.samsung.android.mapsagent
pm uninstall -k --user 0 com.samsung.android.ardrawing
pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall -k --user 0 com.sec.unifiedwfc
pm uninstall -k --user 0 com.sec.android.app.wlantest
