# Preset was created in ADB AppControl 1.6.5
# Total applications: 83
# 8/24/2021 7:04 PM
# Samsung SM-A315G Deleted applications
pm uninstall -k --user 0 com.samsung.aasaservice
pm uninstall -k --user 0 com.google.android.projection.gearhead
pm uninstall -k --user 0 com.google.android.ext.services
pm uninstall -k --user 0 com.aura.oobe.samsung.gl
pm uninstall -k --user 0 com.samsung.android.aremoji
pm uninstall -k --user 0 com.google.ar.core
pm uninstall -k --user 0 com.samsung.android.authfw
pm uninstall -k --user 0 com.sec.android.app.DataCreate
pm uninstall -k --user 0 com.samsung.storyservice
pm uninstall -k --user 0 com.wssyncmldm
pm uninstall -k --user 0 com.android.carrierdefaultapp
pm uninstall -k --user 0 com.samsung.android.knox.containercore
pm uninstall -k --user 0 com.samsung.android.knox.containeragent
pm uninstall -k --user 0 com.samsung.android.app.sharelive
pm uninstall -k --user 0 com.samsung.android.aware.service
pm uninstall -k --user 0 com.samsung.android.mobileservice
pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
pm uninstall -k --user 0 com.samsung.android.cmfa.framework
pm uninstall -k --user 0 com.samsung.cmh
pm uninstall -k --user 0 com.android.providers.partnerbookmarks
pm uninstall -k --user 0 com.sec.epdg
pm uninstall -k --user 0 com.google.android.configupdater
pm uninstall -k --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall -k --user 0 com.google.android.apps.turbo
pm uninstall -k --user 0 com.sec.android.diagmonagent
pm uninstall -k --user 0 com.google.android.as
pm uninstall -k --user 0 com.android.bips
pm uninstall -k --user 0 com.samsung.android.rubin.app
pm uninstall -k --user 0 com.samsung.android.easysetup
pm uninstall -k --user 0 com.samsung.android.dsms
pm uninstall -k --user 0 com.sec.android.provider.emergencymode
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.facebook.services
pm uninstall -k --user 0 com.samsung.android.app.galaxyfinder
pm uninstall -k --user 0 com.google.android.onetimeinitializer
pm uninstall -k --user 0 com.google.android.apps.carrier.carrierwifi
pm uninstall -k --user 0 com.samsung.android.sdk.handwriting
pm uninstall -k --user 0 com.sec.imsservice
pm uninstall -k --user 0 com.samsung.klmsagent
pm uninstall -k --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall -k --user 0 com.sec.android.emergencylauncher
pm uninstall -k --user 0 com.samsung.android.mdx
pm uninstall -k --user 0 com.samsung.android.mdx.kit
pm uninstall -k --user 0 com.samsung.android.mdm
pm uninstall -k --user 0 com.samsung.android.mdx.quickboard
pm uninstall -k --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall -k --user 0 com.netflix.mediaclient
pm uninstall -k --user 0 com.microsoft.skydrive
pm uninstall -k --user 0 com.netflix.partner.activation
pm uninstall -k --user 0 com.google.android.printservice.recommendation
pm uninstall -k --user 0 com.android.printspooler
pm uninstall -k --user 0 com.sec.android.widgetapp.webmanual
pm uninstall -k --user 0 com.osp.app.signin
pm uninstall -k --user 0 com.sec.android.app.billing
pm uninstall -k --user 0 com.samsung.android.scloud
pm uninstall -k --user 0 com.samsung.android.scs
pm uninstall -k --user 0 com.samsung.android.app.spage
pm uninstall -k --user 0 com.sec.location.nsflp2
pm uninstall -k --user 0 com.samsung.android.mcfserver
pm uninstall -k --user 0 com.samsung.android.samsungpass
pm uninstall -k --user 0 com.samsung.android.spayfw
pm uninstall -k --user 0 com.samsung.android.smartsuggestions
pm uninstall -k --user 0 com.samsung.android.sm.policy
pm uninstall -k --user 0 com.samsung.android.secsoundpicker
pm uninstall -k --user 0 com.android.se
pm uninstall -k --user 0 com.sec.sve
pm uninstall -k --user 0 com.sec.location.nfwlocationprivacy
pm uninstall -k --user 0 com.samsung.android.smartcallprovider
pm uninstall -k --user 0 com.sec.android.easyMover.Agent
pm uninstall -k --user 0 com.samsung.android.beaconmanager
pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
pm uninstall -k --user 0 com.samsung.android.accessibility.talkback
pm uninstall -k --user 0 com.trustonic.teeservice
pm uninstall -k --user 0 com.google.android.apps.restore
pm uninstall -k --user 0 com.google.android.setupwizard
pm uninstall -k --user 0 com.google.android.partnersetup
pm uninstall -k --user 0 com.android.managedprovisioning
pm uninstall -k --user 0 com.sec.android.daemonapp
pm uninstall -k --user 0 com.samsung.knox.securefolder
pm uninstall -k --user 0 com.samsung.android.fmm
pm uninstall -k --user 0 com.android.dreams.phototable
pm uninstall -k --user 0 com.samsung.android.kidsinstaller
pm uninstall -k --user 0 com.android.providers.userdictionary
